export declare function capitalize(str: string): string;
export declare function lowerize(str: string): string;
export declare function removeSpaces(str: string): string;
export declare function parenthesize(str: string): string;
export declare function getPowershellValue(val: any): any;
export declare function getAttr(field: any, ...fieldNames: string[]): any;
export declare function hasAttr(field: any, ...fieldNames: string[]): boolean;
export declare function isString(val: any): boolean;
export declare function isObject(val: any): boolean;
export declare function hasItems(obj: any, ...fieldNames: string[]): boolean;
export declare function hasKeys(obj: any, ...fieldNames: string[]): boolean;
