export declare const BuiltInContentType: {
    Item: string;
    item: string;
    Document: string;
    document: string;
    Event: string;
    event: string;
    Issue: string;
    issue: string;
    Announcement: string;
    announcement: string;
    Link: string;
    link: string;
    Contact: string;
    contact: string;
    Message: string;
    message: string;
    Task: string;
    task: string;
    WorkflowHistory: string;
    workflowhistory: string;
    'Workflow History': string;
    Post: string;
    post: string;
    Comment: string;
    comment: string;
    Folder: string;
    folder: string;
    Person: string;
    person: string;
    SharePointGroup: string;
    sharepointgroup: string;
    Picture: string;
    picture: string;
    MasterPage: string;
    masterpage: string;
    masterPage: string;
    'Master Page': string;
    basicPage: string;
    BasicPage: string;
    'Basic Page': string;
    summaryTask: string;
    SummaryTask: string;
    'Summary Task': string;
    articlePage: string;
    ArticlePage: string;
    articlepage: string;
    'Article Page': string;
    page: string;
    Page: string;
    systemPage: string;
    SystemPage: string;
    systempage: string;
    'System Page': string;
    pageLayout: string;
    PageLayout: string;
    pagelayout: string;
    'Page Layout': string;
    welcomePage: string;
    WelcomePage: string;
    welcomepage: string;
    'Welcome Page': string;
};
export declare const FieldTypes: {
    text: string;
    string: string;
    number: string;
    Number: string;
    longtext: string;
    note: string;
    int: string;
    integer: string;
    long: string;
    double: string;
    date: string;
    dateTime: string;
    datetime: string;
    DateTime: string;
    lookup: string;
    computed: string;
    counter: string;
    currency: string;
    file: string;
    choice: string;
    bool: string;
    boolean: string;
    contenttypeid: string;
    lookupmulti: string;
    user: string;
    html: string;
    gridchoice: string;
    multichoice: string;
    multicolumn: string;
    guid: string;
    pageseparator: string;
    recurrence: string;
    threadindex: string;
    threading: string;
    url: string;
    usermulti: string;
    workfloweventtype: string;
    workflowstatus: string;
    taxonomy: string;
    Taxonomy: string;
    taxonomyField: string;
    TaxonomyField: string;
    taxonomyfieldtype: string;
    taxonomyFieldType: string;
    TaxonomyFieldTypeMulti: string;
    taxonomyfieldtypemulti: string;
    taxonomyFieldTypeMulti: string;
};
